language: node_js

sudo: false

notifications:
  slack:
    secure: "bFd+zkP/Eim64Ti8IAgq7k7CbS7Gpp1g890zMqEdPxVkTOqoIzXdoO+Uqabq8AkA0S/seBSdFsTN20wvQK2cNxmShppn1g+3C0iXZrBVwJx8ChnTZXI0EdqKgGbDxjSq06coWN2UFUlM7frKdxnF5uN0/pHqKje5mCKmq+Gpn44="

before_script:
  - bundle install
  - npm install
  - npm install -g bower
  - bower install

script:
  - gulp test
